version: '3.8'

services:
  # 1. The PostgreSQL Database
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  # 2. Redis (Message Broker for Celery)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # 3. The Django Web Application
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_HOST=db
    depends_on:
      - db
      - redis

  # 4. The Celery Worker (For background emails)
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_HOST=db
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: