# Generated by Django 6.0.3 on 2026-03-24 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('email_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='The user who created this campaign.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, help_text='Internal notes about the campaign objectives.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(default=1, help_text='The phishing template to be used for this campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='email_templates.emailtemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user who created this campaign.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcampaign',
            name='description',
            field=models.TextField(blank=True, help_text='Internal notes about the campaign objectives.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcampaign',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The phishing template to be used for this campaign.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='email_templates.emailtemplate'),
        ),
    ]
