# Generated by Django 6.0.3 on 2026-04-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_created_by_campaign_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When the campaign should start sending emails. Leave blank for immediate dispatch.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When the campaign should start sending emails. Leave blank for immediate dispatch.', null=True),
        ),
    ]
