# Generated by Django 6.0.3 on 2026-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_historicaltrackinglink_trackinglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='True if clicked by a known security scanner.'),
        ),
        migrations.AddField(
            model_name='historicalclickevent',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='True if clicked by a known security scanner.'),
        ),
    ]
