# Generated by Django 6.0.3 on 2026-03-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='html_body',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='text_body',
        ),
        migrations.RemoveField(
            model_name='historicalemailtemplate',
            name='html_body',
        ),
        migrations.RemoveField(
            model_name='historicalemailtemplate',
            name='text_body',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(default=1, help_text='The HTML or plain text body of the email.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sender_email',
            field=models.EmailField(default=1, help_text='The email address the email appears to be from.', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sender_name',
            field=models.CharField(default=1, help_text='The name the email appears to be from (e.g., IT Support).', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemailtemplate',
            name='body',
            field=models.TextField(default='test body', help_text='The HTML or plain text body of the email.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemailtemplate',
            name='sender_email',
            field=models.EmailField(default='test@example.com', help_text='The email address the email appears to be from.', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemailtemplate',
            name='sender_name',
            field=models.CharField(default='test sender', help_text='The name the email appears to be from (e.g., IT Support).', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text='Internal name of the template.', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(help_text='The subject line of the phishing email.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='name',
            field=models.CharField(help_text='Internal name of the template.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='subject',
            field=models.CharField(help_text='The subject line of the phishing email.', max_length=255),
        ),
    ]
